let cezalar = [
    { isim: 'Art. 1.01 - Mal uso del claxon', para: 250, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.02 - Invadir el carril contrario', para: 500, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.03 - Giro indebido', para: 350, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.04 - Conducir fuera de la carretera', para: 300, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.05 - Rechazar una orden de la ley', para: 550, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.06 - Vehículo en mal estado', para: 300, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.07 - Estacionar en zonas no habilitadas y obstruir la circulación', para: 400, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.08 - Conducción temerária', para: 650, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.09 - Ignorar señales de tráfico', para: 300, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.10 - Saltarse un semáforo', para: 350, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.11 - Entrada en zona no autorizada', para: 750, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.12 - Conducir sin la licencia correspondiente del vehículo', para: 2000, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.13 - Conducir sin casco en vehículos', para: 300, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.14 - Saltarse un control de tráfico', para: 1000, hapis: 5, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.15 - Circular con un vehículo no apto para la circulación', para: 500, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.16 - Superar el límite de velocidad en vía urbana', para: 700, hapis: 8, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.17 - Superar el límite de velocidad en vía secundaria y autopistas', para: 550, hapis: 8, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.18 - Rebasar una línea continua', para: 270, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.19 -Adelanto en línea continua', para: 325, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.20 - No respetar una señal de STOP ', para: 275, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.21 - Conducir bajo los efectos del alcohol', para: 500, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.22 - Conducir bajo los efectos de sustancias estupefacientes', para: 750, hapis: 5, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.23 - No respetar el paso de peatones', para: 350, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.24 - No usar las luces correspondientes en vía pública', para: 250, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 1.25 - Obstrucción del tráfico', para: 350, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.01 - Disturbios en la vía pública', para: 700, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.02 - Agresión a un civil', para: 2000, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.03 - Faltas de respeto a un civil', para: 500, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.04 - Amenaza verbal a un civil', para: 750, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.05 - Alteración del orden público', para: 500, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.06 - Comercialización ilegal', para: 500, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.07 - Manifestación ilegal', para: 1000, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.08 - Dañar mobiliario urbano', para: 850, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.09 - Acoso psicológico', para: 1500, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.10 - Suplantación de identidad', para: 4000, hapis: 10, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.11 - Racismo / Homofobia', para: 800, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.12 - Circular por la vía pública con el rostro oculto.', para: 520, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.13 - Circular por la vía pública desnudo o semidesnudo', para: 500, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.14 - Negación a identificarse', para: 1000, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.15 - Obstrucción a la justicia', para: 760, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.16 - Violar un perímetro o un cordón policial', para: 1500, hapis: 5, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.17 - Delito de daños', para: 600, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.18 - Violar una orden de alejamiento', para: 3000, hapis: 10, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.19 - Allanamiento de morada', para: 3500, hapis: 0, kamu: 10, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 2.20 - Participación en carreras ilegales', para: 920, hapis: 6, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.01 - Robo de vehículo', para: 1700, hapis: 8, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.02 - Asalto a un civil', para: 3600, hapis: 10, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.03 - Hurto', para: 2000, hapis: 5, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.04 - Robo a un establecimiento comercial', para: 4000, hapis: 10, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.04.1 - Robo a un establecimiento comercial con intento de homicidio', para: 7000, hapis: 15, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.04.2 - Intento de robo a un establecimiento comercial', para: 2000, hapis: 5, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.04.3 - Cómplice de robo a un establecimiento comercial', para: 2000, hapis: 5, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.05 - Robo a Ammu-Nation', para: 5000, hapis: 10, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.05.1 - Robo a Ammu-Nation con intento de homicidio', para: 8000, hapis: 15, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.05.2 - Intento de robo a Ammu-Nation', para: 2500, hapis: 5, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.05.3 - Cómplice de robo a Ammu-Nation', para: 2500, hapis: 5, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.06 - Robo a joyería', para: 10000, hapis: 10, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.06.1 - Robo a joyería con intento de homicidio', para: 15000, hapis: 15, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.06.2 - Intento de robo a joyería', para: 5000, hapis: 5, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.06.3 - Cómplice de robo a joyería', para: 5000, hapis: 5, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.07 - Robo a una Sucursal', para: 15000, hapis: 15, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.07.1 - Robo a una Sucursal con intento de homicidio', para: 20000, hapis: 20, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.07.2 - Intento de robo a una Sucursal', para: 7500, hapis: 10, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 3.07.3 - Cómplice de robo a una Sucursal', para: 7500, hapis: 10, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 4.01 - Exhibición de un arma blanca legal en vía pública ', para: 1750, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 4.02 - Posesión/Exhibición de un arma blanca ilegal en vía pública', para: 3100, hapis: 6, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 4.03 - Posesión/Exhibición de un arma de fuego (bajo calibre)', para: 7000, hapis: 10, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 4.04 - Posesión/Exhibición de un arma de fuego (calibre medio)', para: 10000, hapis: 15, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 4.05 - Posesión/Exhibición de un arma de fuego (alto calibre)', para: 15000, hapis: 20, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 4.06 - Posesión de accesorios', para: 300, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 4.07 - Tráfico de Armas', para: 10000, hapis: 15, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 4.08 - Tráfico de Armas de fuego', para: 20000, hapis: 15, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 5.01 - Posesión de Marihuana', para: 1100, hapis: 10, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 5.02 - Posesión de Cocaína', para: 1700, hapis: 6, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 5.03 - Posesión de Metanfetamina', para: 2200, hapis: 7, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 5.04 - Tráfico de drogas', para: 1500, hapis: 20, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 5.05 - Venta de drogas', para: 1000, hapis: 10, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 5.06 - Consumo de estupefacientes en vía pública', para: 500, hapis: 2, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 6.01 - Intento de secuestro de un civil', para: 4500, hapis: 8, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 6.02 - Secuestro de un civil', para: 7000, hapis: 10, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 6.03.1 - Inteto de homicidio en segundo grado', para: 11000, hapis: 15, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 6.03.2 - Inteto de homicidio en primer grado', para: 15000, hapis: 15, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 6.04.1 - Homicidio en segundo grado', para: 15000, hapis: 15, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 6.04.2 - Homicidio en primer grado', para: 20000, hapis: 15, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art 6.05 - Amenaza o extorsión a un civil', para: 3000, hapis: 7, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 7.01 - Falsificación de documentos', para: 1500, hapis: 5, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 7.02 - Estafa', para: 2000, hapis: 6, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 7.03 - Negación del agente a enseñar el número de placa', para: 3000, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 8.01 - Desacato a la autoridad', para: 1500, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 8.02 - Falta de respeto a un funcionario público', para: 725, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 8.03 - Agredir o amenazar a un funcionario público', para: 1500, hapis: 5, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 8.04 - Robo a un funcionario público o armamento estatal', para: 10000, hapis: 10, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 8.05 - Resistencia al arresto', para: 1200, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 8.06 - Intento de soborno', para: 2000, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 8.07 - Difamar o difundir grabaciones o fotografías de un funcionario público', para: 3100, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 8.08 - Intento de secuestro a un funcionario público', para: 5500, hapis: 10, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 8.09 - Secuestro a un funcionario público', para: 10000, hapis: 15, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 8.10 - Huir de la justicia', para: 3000, hapis: 7, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 8.11 - Suplantación de indentidad de un miembro del estado', para: 3000, hapis: 5, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 8.12 - Mentir o dar falso testimonio', para: 3000, hapis: 7, kamu: 0, illegal: false, active: false, tceza : 1 },
    { isim: 'Art. 9.01 - Porte de +$10000 encima o en el maletero', para: 0, hapis: 0, kamu: 0, illegal: false, active: false, tceza : 1 },
]

